version: 2.1

orbs:
  python: circleci/python@1.5.0

# Define a job to be invoked
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9.5
  
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip

      - run:
          name: build site
          command: mkdocs build \
                   mkdocs gh-deploy

# Invoke jobs via workflows
workflows:
  mkdocs:
    jobs:
      - build-and-test
